sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

language: cpp

compiler: gcc

dist: bionic

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq g++-5 openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-100 libhdf5-openmpi-dev libnetcdf-dev


script:
 - mkdir build && cd build
 - cmake ..
 - make -j2
