jobs:
    - job:
      displayName: pumgen-build
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
        - bash: |
            set -euo pipefail
            export IFS=$'\n\t'
            sudo apt-get update
            sudo apt-get install gcc-8 g++-8 gfortran-9
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
            sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 100
            gcc --version
            sudo apt-get install -qq sudo apt-get install -qq g++-5 openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-100 libhdf5-openmpi-dev libnetcdf-dev
            cd ..
	    # build pumi
	    git clone https://github.com/SCOREC/core.git
	    mkdir core/build
	    cd core/build
	    cmake .. -DCMAKE_C_COMPILER="`which mpicc`" -DCMAKE_CXX_COMPILER="`which mpiCC`" -DCMAKE_C_FLAGS="-O2 -g -Wall" -DCMAKE_CXX_FLAGS="-O2 -g -Wall" -DCMAKE_INSTALL_PREFIX=../../pumi 
	    make -j $(nproc) && make install
	    #Go back to PUMGen and build it
	    cd ../../PUMGen
	    mkdir build && cd build
	    CC=mpicc CXX=mpiCC cmake .. -DCMAKE_PREFIX_PATH=../pumi && make -j $(nproc)
